Traceback (most recent call last):
  File "F:/PyCharmProjects/Automation/Chap10_traceback.py", line 7, in <module>
    raise Exception('This is a exception message !')
Exception: This is a exception message !
